### ISSUE TITLE
Zoomed in views of drilldowns

### ISSUE THREAD

**Issue by eavanvalkenburg** [albero-azure/albero#11]
It is very jarring that the drilldown views are shown with such a large font compared to the main view, would be good to make that uniform!

**Comment by misterious-mister-x** [comment]
Thanks for the feedback. Will try to fix it in the next update.

**Comment by misterious-mister-x** [comment]
Fixed. @eavanvalkenburg can you check if it works as expected ;)  Thanks! Closing for now.

**Comment by eavanvalkenburg** [comment]
Looks great, thanks!
