### ISSUE TITLE
External File format inconsistency with documentation for RC File and ORC.

### ISSUE THREAD

**Issue by Andreas-bersgtedt** [albero-azure/albero#122]
In the Main Decision Tree - Azure Data Dev View RCFile is mentioned in the External file format for Azure Synapse Analytics SQL-On-Demand, 

When clicking thru the links the [Official documentation](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-file-format-transact-sql?view=sql-server-ver15&tabs=rc) states Hive RC File and Hive ORC is not supported with Synapse Analytics (**_This syntax is not supported by serverless SQL pool in Azure Synapse Analytics._**)

**Comment by misterious-mister-x** [comment]
@Andreas-bersgtedt Thank you for the feedback. You are right. I have removed and published it.
