### ISSUE TITLE
Cosmos DB PITR -> Security DT (reliability related)

### ISSUE THREAD

**Issue by misterious-mister-x** [albero-azure/albero#126]
https://devblogs.microsoft.com/cosmosdb/

**Comment by misterious-mister-x** [comment]
Added to the main view

**Comment by elsantorini** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/provision-account-continuous-backup#:~:text=Azure%20Cosmos%20DB%27s%20point%2Din,region%20(where%20backups%20existed).

**Comment by elsantorini** [comment]
You can also add it in the left side Cosmos (under the Append combined with upsert). 
Also PITR is also part of the mysql/postgres/sql etc. Maybe we should add it in the security view instead ?
