### ISSUE TITLE
Reduce overall complexity of the DT

### ISSUE THREAD

**Issue by misterious-mister-x** [albero-azure/albero#39]
There are several ways to achieve this.
One is to move more things into Drill Downs and reduce amount of services directly exposed. 
Please take a look at the picture below.

Thoughts?
![somethoughtsonDT](https://user-images.githubusercontent.com/3391776/100347623-f3d87e80-2fe5-11eb-8187-a85708638b3c.png)

**Comment by misterious-mister-x** [comment]
New version attached. Please comment.
![DTCOre](https://user-images.githubusercontent.com/3391776/101370272-9546b680-38a9-11eb-92df-d09cd23264fe.png)

**Comment by elsantorini** [comment]
<img width="4296" alt="albero_prelaunch" src="https://user-images.githubusercontent.com/39773107/102983768-3f167c00-4515-11eb-836c-08cdf857068a.png">

**Comment by misterious-mister-x** [comment]
@elsantorini thanks for thoughtful review! My answers below.
- Why 24 hours - agree (probably from the past experience) - *will change it*
- Event Triggers - not sure what you mean here - I am referring to a situation when we are doing combination of upsert and append (on top) and combination of sequential reads via Change Feed and Lookups (when both are needed). 
- *I disagree with rephrasing* (please refer to the statement above). This is something which helps us to compare EH with Cosmos on the certain workloads. Cosmos DB is described on the right hand side.
- *Kafka protocol support is one of the main differentiators for EH* especially comparing to Service Bus and IoT Hub so tend to disagree.
- *Agree with the comment on Web Apps* - indeed seems that I have missed this when was compiling current version. 
- TSI / ADX & PBI / AAS - *fully agree* - completely forgot about it.
- On Graph - it is a *good question*. We need to make some extra comparison / will ask some guys for their opinion.

**Comment by elsantorini** [comment]
- **Event Triggers** - I mean that another read pattern might be a case where you read the changes made in the DB and you  trigger other actions. 

- ok, no prob with the rephrasing, just wanted to simplify because basically it uses phrases that are mentioned in the two previous steps (append combined with upsert & storing for long term) 

- For EH vs IoT Hub vs Service Bus- there are other differentiators like max size of throughput supported, or size of message etc. I find these more relevant to write/read patterns than support of a protocol.

**Comment by misterious-mister-x** [comment]
"For EH vs IoT Hub vs Service Bus- there are other differentiators like max size of throughput supported, or size of message etc. I find these more relevant to write/read patterns than support of a protocol."

The thing is that for the overlap below 256 KB of message size and ~8 MBps in (which is where most of the workloads will find themselves) there will be no other differentiator. That said just size of the message and max throughput cannot be identified as safe criteria. Also when it comes to difference between Stream and Queue consistency and functionality of two are much more important (as you typically split streams and queues and do not store / process everything via one gigantic instance). 

Not arguing - just explaining the logic here. Let's also discuss this separately.

**Comment by misterious-mister-x** [comment]
Event Triggering is more on the processing side, no? We need to review this. In case we add Event Triggering it is fair to add Event Grid explicitly with all the integrations.

**Comment by misterious-mister-x** [comment]
- Why 24 hours - removed
- I have added Event Grid and new read pattern (tentatively)
- Rephrasing for Cosmos DB done: "Data can be updated and later should be stored and queried (not sequentially read) for a period longer than EH retention"
- I have rephrased that so EH is "Streaming Semantics" while Service Bus "Queue semantics or Hybrid / FIFO / Exact Once"

**Comment by misterious-mister-x** [comment]
WebApps fixed

**Comment by misterious-mister-x** [comment]
TSI / ADX and PBI / AAS fixed

**Comment by misterious-mister-x** [comment]
Graph changed (not sure if fixed ;)

**Comment by misterious-mister-x** [comment]
![image](https://user-images.githubusercontent.com/3391776/104422158-a788d400-557c-11eb-8b33-9c8a0f4367cf.png)

**Comment by elsantorini** [comment]
Great :) Love it! Two points only:

1. In the event triggering square, you mention ~100s RPS and on the following two squares you mention 5,000 events per sec in the Low/Medium side. Requests in that case mean small batches? 
2. Some difference between Azure SQL and Gremlin can be on the write pattern the following:  

- on Azure SQL you can't store multi-parents for a node
- on Azure SQL many new relationships updates are not supported

**Comment by misterious-mister-x** [comment]
Thanks for all the feedback. Based on discussions & feedback I have crafted the newer version. 
![DT_MajorReview2](https://user-images.githubusercontent.com/3391776/105041180-f5ad4400-5a62-11eb-90a0-05f989eba628.png)
