### ISSUE TITLE
Add Storage Decision Tree

### ISSUE THREAD

**Issue by misterious-mister-x** [albero-azure/albero#46]
I think we need explicitly mention when and why to prefer certain storage option (as per our documentation here): https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-supported-blob-storage-features

This also tightly coupled with DR and fail over approach when it comes to ADLS Gen2 versus Blob, Lifecycle is also currently a part of the story.

**Comment by misterious-mister-x** [comment]
First version will main focus on Blob versus ADLS Gen2 and their support of Delta Lake for Databricks. Other developments will be covered in the new Issue assigned to the Major Review v3.

**Comment by misterious-mister-x** [comment]
Or should we add File / Queue / Table?
![DT Major Review v2 - Storage](https://user-images.githubusercontent.com/3391776/101468559-e0ada300-3943-11eb-88fc-add4e739eb0d.png)

**Comment by misterious-mister-x** [comment]
Delta Lake - we need to make a sub-distinction between OSS DL and Databricks DL before publishing

**Comment by misterious-mister-x** [comment]
![image](https://user-images.githubusercontent.com/3391776/104419898-6c38d600-5579-11eb-91db-157d3c54d9a2.png)
Updated DL

**Comment by LizAntoine** [comment]
> Delta Lake - we need to make a sub-distinction between OSS DL and Databricks DL before publishing

Looks good as discussed.
