### ISSUE TITLE
Power BI Premium decision

### ISSUE THREAD

**Issue by PHenwood** [albero-azure/albero#8]
Just had this shared with me and it looks really good, the linking out from buttons around the techs is a great feature. I believe the Power BI vs AAS bit is a bit misleading.
- There is no DR for Premium - "If a Premium capacity becomes unavailable, workspaces and reports remain accessible and visible to all Power BI Pro licensed users who previously had access to them." So users licensed via Power BI Premium would not have access.
- The limit is 400GB rather than 100TB when compared to AAS, which does depend on the purchased tier. 100TB is the total size for all models.
- I would update the decision for AAS to be something like "Requires query scale-out or Object-level security."

**Comment by misterious-mister-x** [comment]
@LizAntoine what do you think?

**Comment by misterious-mister-x** [comment]
@PHenwood thanks for raising this!

**Comment by misterious-mister-x** [comment]
Hello
After careful review I am proposing the following. 
1. As per PBI Premium (and we are covering PBI Premium here) documentation: "If there is an outage, or an issue that causes Power BI to be inaccessible or inoperable in a region, Power BI fails all its components in that region to a backup instance." https://docs.microsoft.com/en-us/power-bi/admin/service-admin-failover - I am changing DR to failover 
2. On this diagram (as has been explain in the article [https://www.linkedin.com/pulse/how-select-proper-data-backend-technology-azure-andrei-zaichikov](url) as well as in the readme for this document) we are only referring to the absolute max available - not the way how to achieve it. In theory you can split one model into multiple models, etc. 
2a. On the AAS limit - this is the RAM limit I am referring to (different color indicates that - also explained in the article). Surprisingly I wasn't able to find any links to the publicly available storage limits. 
3. Agreed and added to the initial decision process.
@PHenwood please let me know if you have some concerns / comments / further questions.
Closing this for now.
